#!/usr/bin/env bash
set -Eeuo pipefail

# Debian 13 server bootstrap for root environment
# - updates/upgrades system
# - fixes locale
# - installs a lightweight root shell (zsh + starship)
# - installs useful CLI tools inspired by semanticparadox/configs
# - applies safe aliases for bash and zsh
# - disables IPv6 persistently
# - keeps normal ping behavior untouched

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root."
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\n\033[1;33m[warn]\033[0m %s\n' "$*"; }

apt_has_pkg() {
  apt-cache show "$1" >/dev/null 2>&1
}

install_if_available() {
  local pkg
  local to_install=()
  for pkg in "$@"; do
    if apt_has_pkg "$pkg"; then
      to_install+=("$pkg")
    else
      warn "Package not available on this host: $pkg"
    fi
  done
  if ((${#to_install[@]})); then
    apt-get install -y "${to_install[@]}"
  fi
}

ensure_locale() {
  log "Fixing locale"
  install_if_available locales
  grep -q '^en_US.UTF-8 UTF-8$' /etc/locale.gen || echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
  locale-gen en_US.UTF-8
  update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
  cat >/etc/default/locale <<'EOF'
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
EOF
}

system_update() {
  log "Updating APT metadata"
  apt-get update
  log "Upgrading installed packages"
  apt-get upgrade -y
}

install_cli_tools() {
  log "Installing base tools"
  install_if_available \
    ca-certificates curl wget git gnupg2 unzip zip tar xz-utils \
    jq less nano neovim bash-completion \
    tmux btop tree lsof strace rsync sudo software-properties-common \
    iputils-ping traceroute dnsutils whois pv tcpdump nmap fzf zoxide \
    ripgrep fd-find bat eza duf dust starship zsh
}

install_optional_tools() {
  log "Installing optional extras when available"
  install_if_available bandwhich
}

disable_ipv6() {
  log "Disabling IPv6 persistently"
  cat >/etc/sysctl.d/99-disable-ipv6.conf <<'EOF'
# Managed by debian13-master-bootstrap.sh
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
  sysctl --system >/dev/null || true
}

setup_root_shell() {
  log "Configuring root shell"
  mkdir -p /root/.config/shell /root/.config/starship

  cat >/root/.config/shell/greeting.sh <<'EOF'
# Generated by debian13-master-bootstrap.sh
if [[ -n "${SSH_CONNECTION:-}" && -z "${ROOT_GREETING_SHOWN:-}" ]]; then
  export ROOT_GREETING_SHOWN=1
  echo
  echo "Welcome back, root."
  echo "Useful commands:"
  echo "  ls/ll/lt - eza-powered listing"
  echo "  cat      - bat with syntax highlighting"
  echo "  find     - fd/fdfind"
  echo "  vi/vim/v - neovim"
  echo "  top/htop - btop"
  echo "  df       - duf"
  echo "  du       - dust"
  echo "  t        - attach/create tmux session"
  echo "  ports    - listening sockets"
  echo "  ping4    - force IPv4 ping"
  echo "  myip     - show public IPv4"
  echo "  originals: gls gcat gfind gtop gdf gdu"
  echo
fi
EOF

  cat >/root/.config/starship.toml <<'EOF'
add_newline = false
format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"

[username]
show_always = true
format = "[$user]($style)@"
style_root = "bold red"
style_user = "bold green"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold yellow"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "git:"
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"

[cmd_duration]
min_time = 1000
format = "[took $duration]($style) "
style = "dimmed white"

[character]
success_symbol = "[#](bold green) "
error_symbol = "[#](bold red) "
EOF

  cat >/root/.config/shell/aliases.common <<'EOF'
# Generated by debian13-master-bootstrap.sh

# improved replacements over common defaults
if command -v eza >/dev/null 2>&1; then
  alias ls='eza'
  alias ll='eza -lah --git'
  alias la='eza -a'
  alias lt='eza -T'
fi

if command -v batcat >/dev/null 2>&1; then
  alias cat='batcat --paging=never'
  alias catp='batcat'
elif command -v bat >/dev/null 2>&1; then
  alias cat='bat --paging=never'
  alias catp='bat'
fi

if command -v fdfind >/dev/null 2>&1; then
  alias find='fdfind'
elif command -v fd >/dev/null 2>&1; then
  alias find='fd'
fi

if command -v nvim >/dev/null 2>&1; then
  alias vim='nvim'
  alias vi='nvim'
  alias v='nvim'
fi

if command -v btop >/dev/null 2>&1; then
  alias top='btop'
  alias htop='btop'
fi

if command -v duf >/dev/null 2>&1; then
  alias df='duf'
fi

if command -v dust >/dev/null 2>&1; then
  alias du='dust'
fi

# keep access to originals
alias gls='/usr/bin/ls'
alias gcat='/usr/bin/cat'
alias gfind='/usr/bin/find'
alias gtop='/usr/bin/top'
alias gdf='/usr/bin/df'
alias gdu='/usr/bin/du'

# quality-of-life
alias cls='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias svim='sudo -E nvim'
alias t='tmux new -A -s main'
alias ports='ss -tulpn'
alias ping4='ping -4'
alias myip='curl -4 -fsSL ifconfig.me ; echo'
EOF

  cat >/root/.bashrc <<'EOF'
# Generated by debian13-master-bootstrap.sh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export BAT_PAGER=""

[[ -f /etc/bash_completion ]] && . /etc/bash_completion
[[ -f /root/.config/shell/aliases.common ]] && . /root/.config/shell/aliases.common
[[ -f /root/.config/shell/greeting.sh ]] && . /root/.config/shell/greeting.sh

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init bash)"
fi
if command -v fzf >/dev/null 2>&1; then
  export FZF_DEFAULT_OPTS="--height=40% --border"
fi
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init bash)"
fi
EOF

  cat >/root/.zshrc <<'EOF'
# Generated by debian13-master-bootstrap.sh
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export BAT_PAGER=""

autoload -Uz compinit && compinit
setopt autocd interactivecomments no_beep hist_ignore_dups share_history
HISTSIZE=50000
SAVEHIST=50000

[[ -f /root/.config/shell/aliases.common ]] && source /root/.config/shell/aliases.common
[[ -f /root/.config/shell/greeting.sh ]] && source /root/.config/shell/greeting.sh

if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi
if command -v fzf >/dev/null 2>&1; then
  export FZF_DEFAULT_OPTS="--height=40% --border"
fi
if command -v starship >/dev/null 2>&1; then
  eval "$(starship init zsh)"
fi
EOF

  if command -v zsh >/dev/null 2>&1; then
    chsh -s "$(command -v zsh)" root || true
  fi
}

print_summary() {
  log "Bootstrap complete"
  echo "Key points:"
  echo "  - root shell: zsh (if installed)"
  echo "  - prompt: starship"
  echo "  - IPv6: disabled in /etc/sysctl.d/99-disable-ipv6.conf"
  echo "  - ping kept as the standard system ping"
  echo "  - aliases loaded for both /root/.bashrc and /root/.zshrc"
  echo
  echo "Open a new SSH session to see the final shell/prompt."
}

main() {
  system_update
  ensure_locale
  install_cli_tools
  install_optional_tools
  setup_root_shell
  disable_ipv6
  print_summary
}

main "$@"
