#!/usr/bin/env bash
set -euo pipefail

log() { printf "\n\033[1m%s\033[0m\n" "$*"; }

# Files
FISH_ALIASES="$HOME/.config/fish/conf.d/aliases.fish"
ZSH_ALIASES="$HOME/.config/shell/aliases.zsh"
BASH_ALIASES="$HOME/.config/shell/aliases.bash"

ensure_dirs() {
  mkdir -p "$HOME/.config/fish/conf.d"
  mkdir -p "$HOME/.config/shell"
  touch "$HOME/.zshrc" "$HOME/.bashrc"
}

write_fish_aliases() {
  log "Writing fish aliases: $FISH_ALIASES"
  cat > "$FISH_ALIASES" <<'EOF'
# Generated by install-aliases.sh

# ---- Safe replacements ----
if type -q eza
  alias ls="eza"
  alias ll="eza -lah"
  alias la="eza -a"
  alias lt="eza -T"
end

if type -q bat
  alias cat="bat"
end

if type -q rg
  alias grep="rg"
end

if type -q fd
  alias find="fd"
end

if type -q nvim
  alias vim="nvim"
  alias vi="nvim"
end

if type -q btop
  alias top="btop"
end

if type -q duf
  alias df="duf"
end

if type -q dust
  alias du="dust"
end

# ---- Keep access to originals when needed ----
# macOS default grep/find are still available as /usr/bin/grep and /usr/bin/find
alias ggrep="/usr/bin/grep"
alias gfind="/usr/bin/find"
alias gls="/bin/ls"
alias gcat="/bin/cat"

# ---- Optional (uncomment if you really want) ----
# if type -q gping
#   alias ping="gping"
# end
# if type -q curlie
#   alias curl="curlie"
# end

# zoxide: keep both, do NOT replace cd by default
# if type -q zoxide
#   zoxide init fish | source
# end

# ---- Modus terminal theme switch (Alacritty) ----
alias modus-light="cp ~/.config/alacritty/themes/modus_operandi_tinted.toml ~/.config/alacritty/themes/current.toml"
alias modus-dark="cp ~/.config/alacritty/themes/modus_vivendi.toml ~/.config/alacritty/themes/current.toml"
EOF
}

write_zsh_aliases() {
  log "Writing zsh aliases: $ZSH_ALIASES"
  cat > "$ZSH_ALIASES" <<'EOF'
# Generated by install-aliases.sh

# ---- Safe replacements ----
command -v eza >/dev/null 2>&1 && alias ls='eza' && alias ll='eza -lah' && alias la='eza -a' && alias lt='eza -T'
command -v bat >/dev/null 2>&1 && alias cat='bat'
command -v rg  >/dev/null 2>&1 && alias grep='rg'
command -v fd  >/dev/null 2>&1 && alias find='fd'
command -v nvim >/dev/null 2>&1 && alias vim='nvim' && alias vi='nvim'
command -v btop >/dev/null 2>&1 && alias top='btop'
command -v duf  >/dev/null 2>&1 && alias df='duf'
command -v dust >/dev/null 2>&1 && alias du='dust'

# ---- Originals ----
alias ggrep='/usr/bin/grep'
alias gfind='/usr/bin/find'
alias gls='/bin/ls'
alias gcat='/bin/cat'

# ---- Optional ----
# command -v gping >/dev/null 2>&1 && alias ping='gping'
# command -v curlie >/dev/null 2>&1 && alias curl='curlie'

# zoxide: recommended as separate command `z`, not replacing `cd`

# ---- Modus terminal theme switch (Alacritty) ----
alias modus-light='cp ~/.config/alacritty/themes/modus_operandi_tinted.toml ~/.config/alacritty/themes/current.toml'
alias modus-dark='cp ~/.config/alacritty/themes/modus_vivendi.toml ~/.config/alacritty/themes/current.toml'
EOF
}

write_bash_aliases() {
  log "Writing bash aliases: $BASH_ALIASES"
  cat > "$BASH_ALIASES" <<'EOF'
# Generated by install-aliases.sh

# ---- Safe replacements ----
command -v eza >/dev/null 2>&1 && alias ls='eza' && alias ll='eza -lah' && alias la='eza -a' && alias lt='eza -T'
command -v bat >/dev/null 2>&1 && alias cat='bat'
command -v rg  >/dev/null 2>&1 && alias grep='rg'
command -v fd  >/dev/null 2>&1 && alias find='fd'
command -v nvim >/dev/null 2>&1 && alias vim='nvim' && alias vi='nvim'
command -v btop >/dev/null 2>&1 && alias top='btop'
command -v duf  >/dev/null 2>&1 && alias df='duf'
command -v dust >/dev/null 2>&1 && alias du='dust'

# ---- Originals ----
alias ggrep='/usr/bin/grep'
alias gfind='/usr/bin/find'
alias gls='/bin/ls'
alias gcat='/bin/cat'

# ---- Optional ----
# command -v gping >/dev/null 2>&1 && alias ping='gping'
# command -v curlie >/dev/null 2>&1 && alias curl='curlie'

# zoxide: recommended as separate command `z`, not replacing `cd`

# ---- Modus terminal theme switch (Alacritty) ----
alias modus-light='cp ~/.config/alacritty/themes/modus_operandi_tinted.toml ~/.config/alacritty/themes/current.toml'
alias modus-dark='cp ~/.config/alacritty/themes/modus_vivendi.toml ~/.config/alacritty/themes/current.toml'
EOF
}

hook_shell_rcs() {
  log "Hooking aliases into zsh/bash rc files..."

  # zsh: source aliases if not already
  if ! grep -q "aliases.zsh" "$HOME/.zshrc"; then
    cat >> "$HOME/.zshrc" <<EOF

# Added by install-aliases.sh
if [ -f "$ZSH_ALIASES" ]; then
  source "$ZSH_ALIASES"
fi
EOF
  fi

  # bash: source aliases if not already
  if ! grep -q "aliases.bash" "$HOME/.bashrc"; then
    cat >> "$HOME/.bashrc" <<EOF

# Added by install-aliases.sh
if [ -f "$BASH_ALIASES" ]; then
  source "$BASH_ALIASES"
fi
EOF
  fi
}

main() {
  ensure_dirs
  write_fish_aliases
  write_zsh_aliases
  write_bash_aliases
  hook_shell_rcs

  log "Done."
  echo "Open a new terminal, or run: source ~/.zshrc / source ~/.bashrc, or restart fish."
  echo "Quick check: ls, cat, grep, find, df, du, top, vim"
}

main "$@"
